version: '2'
services:
  ammurapi:
    image: kolyabres/ammurapi_php:latest
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/ammurapi
    environment:
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    links:
      - mysql
      - mysql_test
    tty: true
    command: ./docker/run.sh
  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  mysql_test:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}